### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by andresbott** [2amigos/yii2-multi-select-widget#1]
Hi, please make a litte better documentation
i had to dig into the code.

please add  some examples like this:

   echo    MultiSelect::widget([
        'id'=>"multiXX",
         "options"=>['multiple'=>"multiple"], // for the actual multiselect
         'data' => [0=>'super', 2=>'natural'], // data as array
         'name' => 'multti', // name for the form
         "clientOptions"=>["includeSelectAllOption"=>true,'numberDisplayed'=>2], // js options
            ]);

also refear that if a model is provided, the model is used;
i asume with option "model"=>$model (did not try it)

**Comment by xenogenesi** [comment]
To get the `value` working and get pre-selected items I had to put it into `options`

    "options" => ['multiple'=>"multiple",  "value"=>[0,2] ]

**Comment by shokhaa** [comment]
how to multiple selected many object? 
actionUpdate
        $cat = Category::find()->all();

        $categoryEmploye = CategoryEmploye::find()->where(['employe_id' => $model->id])->a;;();


view
