### ISSUE TITLE
Not possible to use widget options that need a callback as a parameter

### ISSUE THREAD

**Issue by trombipeti** [2amigos/yii2-multi-select-widget#13]
Use case: I would like to set e.g. the [buttonText](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-buttonText) (or any other that needs a callback) option for the widget from PHP. It is not possible though.

Cause of the problem: "clientOptions" is Json::encode()-ed which essentially converts the function body to a string.

Proposed solution: Maybe something like:
'clientOptions' => [ 'buttonText' => ['callback' => "function(options, select) { return '42'; }" ]
And then parse it accordingly.

If I missed something and this is already possible, please tell me how.

**Comment by tonydspaniard** [comment]
@trombipeti to use a callback function, is documented to use the `JsExperession` class from Yii2. Try this: 

```
'clientOptions' => [ 'buttonText' => ['callback' => new JsExpression("function(options, select) { return '42'; }") ]

**Comment by trombipeti** [comment]
Wow I didn't know that, thank you!
