### ISSUE TITLE
Please either update repo or remove It :(

### ISSUE THREAD

**Issue by shantinath** [2amigos/yii2-multi-select-widget#14]

**Comment by tonydspaniard** [comment]
A bit of help is always welcome ;)

**Comment by mtangoo** [comment]
@shantinath that is rude. We do not pay @tonydspaniard anything to giveaway all these stuffs. Learn to be thankful. If you have a buck contact hime, pay him for better service ;)
http://2amigos.us/

**Comment by tonydspaniard** [comment]
Dear @mtangoo I have updated the library documentation and added tests. All this work is to show my gratitude to you specially for your kindness and words. Everything I give away is exactly for people like you. 

Thank you very much.

**Comment by mtangoo** [comment]
Hi @tonydspaniard, 

>Dear @mtangoo I have updated the library documentation and added tests. All this work is to show >my gratitude to you specially for your kindness and words. Everything I give away is exactly for >people like you.
>
>Thank you very much.

You are welcome, sir! Just know there are some of us who appreciate your efforts!

**Comment by shantinath** [comment]
If there was no devil, then no one knew God. Thanks :)

**Comment by tonydspaniard** [comment]
@shantinath definitely you made me work on it.
