### ISSUE TITLE
Multiple preselected with model

### ISSUE THREAD

**Issue by agaplus** [2amigos/yii2-multi-select-widget#4]
Preselect with 'model' and 'attribute' instead of 'name' and 'value'' works if the preselect is only one. Or maybe i not pass a valid data...

``` php
echo MultiSelect::widget([
                    "options" => ['multiple'=>"multiple"], // for the actual multiselect
                    'data' =>  $listData,
                    'model' => $model,
                    'attribute' => "centro_id",
                    "clientOptions" =>
                        [
                            "includeSelectAllOption" => false,
                            'numberDisplayed' => 3,
                        ],
                ]);
```

how can I do?

**Comment by tonydspaniard** [comment]
Whats `$listData`?

**Comment by agaplus** [comment]
$centri = Centro::find()->all();
$listDatai=ArrayHelper::map($centri,'id','nome');

**Comment by tonydspaniard** [comment]
I have to refactor this application for the new http://yiiwheels.com site. Will handle this issue when doing it. 

Thanks.

**Comment by tonydspaniard** [comment]
Nevertheless, how are you going to preselect multiple? Is the attribute an array? have you seen this: https://github.com/2amigos/yii2-multi-select-widget/issues/1#issuecomment-47092009

**Comment by ilaiya11** [comment]
Not supported for Yii2 Modal popup.
