### ISSUE TITLE
in MultiSelectListBox does not work functions

### ISSUE THREAD

**Issue by strafun** [2amigos/yii2-multi-select-widget#5]
afterInit	
afterSelect	
afterDeselect
values json_encode convert to string, But script neded function.
i sloved problem with this http://solutoire.com/2008/06/12/sending-javascript-functions-over-json/
but maybe in Yii isset method that already slove this problem.

**Comment by tonydspaniard** [comment]
Have you done?: 

```php 
'afterInit' => new JsExpression('function(){...}')
```

**Comment by strafun** [comment]
Nice! That what i'm look info. gracias))
May be you know how to init widget with already seleccted values and "keepOrder" => true? For now it do not keep order.

**Comment by tonydspaniard** [comment]
@strafun you will have to provide the "data" ordered by your self (have you tried orderBy in your queries or sorting the array?) The plugin just renders the items you provide. 

Best!
